create table if not exists public.songs (
    id uuid primary key,
    archived boolean not null default false,
    title text not null,
    subtitle text not null default '',
    composer text not null,
    image text not null default '',
    audio text not null default '',
    measure_count integer not null default 0,
    elapsed_time integer not null default 0,
    created_at timestamptz not null default now()
);

create table if not exists public.measures (
    id uuid primary key default gen_random_uuid(),
    song_id uuid not null references public.songs(id) on delete cascade,
    number integer not null,
    initial numeric not null default 0,
    target numeric not null default 0,
    ignore_tempo boolean not null default false,
    mode text not null default 'stability' check (mode in ('rapid', 'speed', 'stability')),
    elapsed_time integer not null default 0,
    last_event_at bigint,
    last_metronome_bpm numeric,
    success_count integer not null default 0,
    event_count integer not null default 0,
    unique (song_id, number)
);

create table if not exists public.practice_events (
    id bigint generated by default as identity primary key,
    measure_id uuid not null references public.measures(id) on delete cascade,
    timestamp bigint not null,
    type text not null,
    value numeric,
    outcome text not null check (outcome in ('success', 'failure'))
);

create index if not exists practice_events_measure_id_timestamp_idx
    on public.practice_events (measure_id, timestamp desc);

alter table public.songs enable row level security;
alter table public.measures enable row level security;
alter table public.practice_events enable row level security;
